openapi: 3.0.2
info:
  version: 1.0.0
  title: the-index
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  description: >
    API documentation for the-index.
externalDocs:
  description: GitHub
  url: 'https://github.com/s-thom/the-index'
servers:
  - url: 'https://the-index.sthom.kiwi/api'
paths:
  /login:
    $ref: ./paths/login.yaml
  /tags:
    $ref: ./paths/tags.yaml
  /search:
    $ref: ./paths/search.yaml
  /links:
    $ref: ./paths/links/index.yaml
  /links/{id}:
    $ref: ./paths/links/id.yaml
components:
  securitySchemes:
    bearer:
      type: http
      description: Authenticatin by bearer token
      scheme: bearer
      bearerFormat: JWT
