openapi: 3.0.2
info:
  version: 1.0.0
  title: the-index
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  description: >
    API documentation for the-index.
externalDocs:
  description: GitHub
  url: 'https://github.com/s-thom/the-index'
servers:
  - url: 'https://the-index.sthom.kiwi/api'
paths:
  /v2/auth:
    $ref: ./paths/v2/auth.yaml
  /v2/links:
    $ref: ./paths/v2/links/index.yaml
  /v2/links/{id}:
    $ref: ./paths/v2/links/{id}.yaml
  /v2/tags:
    $ref: ./paths/v2/tags.yaml
  /v2/users/{name}:
    $ref: ./paths/v2/users/{name}.yaml
components:
  securitySchemes:
    cookie:
      type: apiKey
      description: Authentication by session cookie
      in: cookie
      name: session
