/* Generated by restful-react */

import { customGet, customMutate, CustomGetProps, CustomMutateProps } from './util/fetchers';
/**
 * Login request with no credentials
 */
export interface PostLoginRequest {
  /**
   * The name of the user logging in
   */
  name: string;
}

/**
 * Login request with a TOTP code
 */
export interface PostLoginTOTPRequest {
  /**
   * The name of the user logging in
   */
  name: string;
  /**
   * The challenge issued
   */
  challenge: 'TOTP';
  /**
   * The response to the challenge
   */
  response: string;
}

/**
 * Successful response
 */
export interface PostLoginSuccessResponse {
  /**
   * The JWT bearer token
   */
  token: string;
  /**
   * The decoded content of the token
   */
  content: {
    /**
     * The ID of the user
     */
    userId: string;
  };
}

/**
 * Challenge required response
 */
export interface PostLoginChallengeResponse {
  /**
   * A code referring to why the user was not authorised
   */
  requires: 'challenge';
  /**
   * Whether TOTP can be used to satisfy the challenge
   */
  totp: boolean;
}

/**
 * Setup required response
 */
export interface PostLoginSetupResponse {
  /**
   * A code referring to why the user was not authorised
   */
  requires: 'setup';
  /**
   * The secret code for TOTP authentication
   */
  code: string;
  /**
   * A URL that can be used to import the TOTP secret into an authenticator app
   */
  url: string;
}

/**
 * A link stored in the-index
 */
export interface LinkDetail {
  /**
   * The ID of the link
   */
  id: string;
  /**
   * The URL of the link
   */
  url: string;
  /**
   * List of tags associated with the link
   */
  tags: string[];
  /**
   * The date the link was added
   */
  inserted: string;
  /**
   * The user that added the link
   */
  user: {
    /**
     * The ID of the user
     */
    id: string;
    /**
     * The name of the user
     */
    name: string;
  };
}

/**
 * An error
 */
export interface Error {
  /**
   * A unique identifier for this particular occurrence of the problem
   */
  id: string;
  /**
   * An application-specific error code
   */
  code?: string;
  /**
   * A human-readable explanation of the problem
   */
  detail?: string;
  /**
   * The HTTP status code applicable to the problem
   */
  status?: string;
  /**
   * An object containing additional information about the problem
   */
  meta?: { [key: string]: any };
}

/**
 * Response for when problems occur in the application
 */
export interface ErrorResponseResponse {
  /**
   * List of errors
   */
  errors: Error[];
}

/**
 * Log in
 *
 * Log in to the-index
 *
 */
export function postLogin(
  props: CustomMutateProps<
    PostLoginSuccessResponse | PostLoginChallengeResponse | PostLoginSetupResponse,
    void,
    void,
    PostLoginRequest | PostLoginTOTPRequest,
    void
  >,
) {
  return customMutate<
    PostLoginSuccessResponse | PostLoginChallengeResponse | PostLoginSetupResponse,
    void,
    void,
    PostLoginRequest | PostLoginTOTPRequest,
    void
  >('POST', `/login`, props);
}

export interface GetTagsResponse {
  /**
   * The list of tags
   */
  tags: string[];
}

export interface GetTagsQueryParams {
  /**
   * List of tags to exclude
   */
  excludeTags?: string[];
}

/**
 * Get common tags
 *
 * Gets a list of the most commonly used tags by the current user
 *
 */
export function getTags(props: CustomGetProps<GetTagsResponse, void, GetTagsQueryParams, void>) {
  return customGet<GetTagsResponse, void, GetTagsQueryParams, void>(`/tags`, props);
}

export interface PostSearchResponse {
  /**
   * The list of links
   */
  links: LinkDetail[];
}

export interface PostSearchQueryParams {
  /**
   * List of tags to exclude
   */
  excludeTags?: string[];
}

export interface PostSearchRequestBody {
  /**
   * List of tags to search on
   */
  tags: string[];
  /**
   * The upper bound for the time a link was added
   */
  before?: string;
  /**
   * The lower bound for the time a link was added
   */
  after?: string;
}

/**
 * Search links
 *
 * Searches for links matching the given parameters
 *
 */
export function postSearch(
  props: CustomMutateProps<PostSearchResponse, void, PostSearchQueryParams, PostSearchRequestBody, void>,
) {
  return customMutate<PostSearchResponse, void, PostSearchQueryParams, PostSearchRequestBody, void>(
    'POST',
    `/search`,
    props,
  );
}

export interface PostLinksResponse {
  /**
   * The ID of the newly added link
   */
  id: string;
}

export interface PostLinksRequestBody {
  /**
   * The link to be added
   */
  url: string;
  /**
   * List of tags to add to the link
   */
  tags: string[];
}

/**
 * Add new link
 *
 * Adds a new link
 *
 */
export function postLinks(props: CustomMutateProps<PostLinksResponse, void, void, PostLinksRequestBody, void>) {
  return customMutate<PostLinksResponse, void, void, PostLinksRequestBody, void>('POST', `/links`, props);
}

export interface GetLinksIdResponse {
  link: LinkDetail;
}

export interface GetLinksIdPathParams {
  /**
   * The ID of the link
   */
  id: string;
}

/**
 * Get link detail
 *
 * Gets the detail of a single link
 *
 */
export function getLinksId({
  id,
  ...props
}: CustomGetProps<GetLinksIdResponse, void, void, GetLinksIdPathParams> & {
  /**
   * The ID of the link
   */
  id: string;
}) {
  return customGet<GetLinksIdResponse, void, void, GetLinksIdPathParams>(`/links/${id}`, props);
}

export interface GetV2LinksResponse {
  /**
   * The list of links
   */
  links: LinkDetail[];
}

export interface GetV2LinksQueryParams {
  /**
   * List of tags to include
   */
  tags?: string[];
  /**
   * The upper bound for the time a link was added
   */
  before?: string;
  /**
   * The lower bound for the time a link was added
   */
  after?: string;
}

/**
 * Search links
 *
 * Searches for links matching the given parameters
 *
 */
export function getV2Links(
  props: CustomGetProps<GetV2LinksResponse, ErrorResponseResponse, GetV2LinksQueryParams, void>,
) {
  return customGet<GetV2LinksResponse, ErrorResponseResponse, GetV2LinksQueryParams, void>(`/v2/links`, props);
}

export interface PostV2LinksResponse {
  link: LinkDetail;
}

export interface PostV2LinksRequestBody {
  /**
   * The link to be added
   */
  url: string;
  /**
   * List of tags to add to the link
   */
  tags: string[];
}

/**
 * Add new link
 *
 * Adds a new link
 *
 */
export function postV2Links(
  props: CustomMutateProps<PostV2LinksResponse, ErrorResponseResponse, void, PostV2LinksRequestBody, void>,
) {
  return customMutate<PostV2LinksResponse, ErrorResponseResponse, void, PostV2LinksRequestBody, void>(
    'POST',
    `/v2/links`,
    props,
  );
}

export interface GetV2LinkIdResponse {
  link: LinkDetail;
}

export interface GetV2LinkIdPathParams {
  /**
   * The ID of the link
   */
  id: string;
}

/**
 * Get link detail
 *
 * Gets the detail of a single link
 *
 */
export function getV2LinkId({
  id,
  ...props
}: CustomGetProps<GetV2LinkIdResponse, ErrorResponseResponse, void, GetV2LinkIdPathParams> & {
  /**
   * The ID of the link
   */
  id: string;
}) {
  return customGet<GetV2LinkIdResponse, ErrorResponseResponse, void, GetV2LinkIdPathParams>(`/v2/links/${id}`, props);
}

export interface GetV2TagsResponse {
  /**
   * The list of tags
   */
  tags: string[];
}

export interface GetV2TagsQueryParams {
  /**
   * List of tags to exclude
   */
  exclude?: string[];
}

/**
 * Get common tags
 *
 * Gets a list of the most commonly used tags by the current user
 *
 */
export function getV2Tags(props: CustomGetProps<GetV2TagsResponse, ErrorResponseResponse, GetV2TagsQueryParams, void>) {
  return customGet<GetV2TagsResponse, ErrorResponseResponse, GetV2TagsQueryParams, void>(`/v2/tags`, props);
}
