name: Backend # Based on GitHub template
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        env:
          CI: "true"
          DB_PATH: database.sqlite
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          npm ci
          lerna bootstrap
          cd packages/backend
          npm run build --if-present
          npm test
  database:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, run migration
        env:
          CI: "true"
          FLYWAY_URL: jdbc:sqlite:database.sqlite
          FLYWAY_USER: ${{ secrets.FLYWAY_USER }}
          FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}
        run: |
          npm ci
          lerna bootstrap
          cd packages/backend
          npm run migrate
