name: Docker
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - frontend
          - backend
          - database-migration
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/s-thom/the-index/${{ matrix.image }}
          tag-sha: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            {{major}}.{{minor}}.{{patch}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.image }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-${{ matrix.image }}-
      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: './docker/${{ matrix.image }}.Dockerfile'
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platform: linux/amd64,linux/arm64,linux/386,linux/arm32v7,linux/arm64v8
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/s-thom/the-index/${{ matrix.image }}:latest
