name: Docker
on:
  push:
jobs:
  build-image:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      matrix:
        image:
          - frontend
          - backend
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.image }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-${{ matrix.image }}-
      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          push: true
          file: './docker/${{ matrix.image }}.Dockerfile'
          tags: localhost:5000/s-thom/the-index/${{ matrix.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/s-thom/the-index/${{ matrix.image }}:latest
