name: Frontend # Based on GitHub template
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        env:
          CI: "true"
        run: |
          npm ci
          npx lerna bootstrap
          cd packages/frontend
          npm run build --if-present
          npm test
